modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dbi"
version="1.0.0"
displayName="Dragon Block Infinity"
authors="Bernardo"
description='''
Mod de ra√ßas e sistema inspirado em Dragon Ball.
'''

[[dependencies.dbi]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dbi]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"]]