modLoader="javafml"  
loaderVersion="[47,)"  
license="All Rights Reserved"

[[mods]]
modId="dragonblockinfinity"
version="1.0.0"
displayName="Dragon Block Infinity"
updateJSONURL=""
displayURL="https://example.com"
logoFile="assets/dragonblockinfinity/textures/minecraft_style_dragon_ball_landscape.png"
credits="Inspired by DragonBlock C"
authors="Bernardo"

description='''
Dragon Block Infinity é um mod inspirado em Dragon Ball e no lendário mod DragonBlock C.
Ele traz sistemas de Ki, raças, transformações e mundos como Namekusei e Terra.
Desenvolvido com amor e energia infinita!
'''

[[dependencies.dragonblockinfinity]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dragonblockinfinity]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
